# Generated by Django 3.1.7 on 2021-10-04 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='picture',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
