# Generated by Django 3.2.5 on 2021-10-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0002_artwork_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='about',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
